version: "3.9"
services:
    php:
        image: mobtitude/php-xdebug:8.0-cli
        entrypoint: [ "/usr/local/bin/php" ]
        ports:
            - "9000:9000"
        volumes:
            - ./:/app
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
